server:
  port: 8010
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unnamed_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 123456
  druid:
      initial-size: 40
      max-active: 50
      min-idle: 30
      max-wait: 60000
      test-on-borrow: true
      test-while-idle: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml